config/routes.rb
Rails.application.routes.draw do

  get 'dashboard' => 'users#dashboard', as: "user_dashboard"

  get 'profile/:id' => 'users#show', as: "user_profile"

  resources :conversations, only: [:index, :show] do
    resources :messages, only: [:create]
  end


  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
    root to: 'pages#home'

  resources :cellars, only: [:index, :show, :create, :update, :destroy] do
    resources :reservations, only: [:create, :new, :show, :destroy, :update]
    resources :messages, only: [:create, :new, :index]
  end

  resources :reservations, only: [] do
    resources :reservation_bottles, only: [:create, :show, :destroy]
  end

  namespace :admin do
    resources :bottle_lots, only: [:new, :index, :create, :show]
    resources :cellars, only: [:new, :index, :edit]
    resources :reservations, only: [:index, :show]
  end

  mount Attachinary::Engine => "/attachinary"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bottle_lot.rb
class BottleLot < ApplicationRecord
  belongs_to :user
  has_many :reservation_bottles
  has_many :reservations, through: :reservation_bottles

  validates :year, presence: true
  validates :appelation, presence: true
  validates :quantity, presence: true


  def to_s
    "#{dimension} - #{quantity}"
  end

end

app/models/cave.rb
class Cave < ApplicationRecord
  belongs_to :user
  has_many :reservations, dependent: :destroy
  has_many :messages, dependent: :destroy

  validates :description, presence: true
  validates :address, presence: true
  validates :price_per_month, presence: true
  validates :type, presence: true

end

app/models/cellar.rb
class Cellar < ApplicationRecord
  belongs_to :user
  has_many :reservations, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :conversations, dependent: :destroy

  validates :description, presence: true
  validates :address, presence: true
  validates :price_per_month, presence: true
  validates :kind, presence: true

  has_attachments :photos, maximum: 3

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  def any_reviews?
    self.reservations.any? { |reservation| reservation.review.present? }
  end

end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :user
  belongs_to :cellar
  has_many :messages
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :conversation

  validates :content, presence: true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :cellar
  belongs_to :user
  has_many :reservation_bottles
  has_many :bottle_lots, through: :reservation_bottles

  validates :check_in, presence: true
  validates :check_out, presence: true

end

app/models/reservation_bottle.rb
class ReservationBottle < ApplicationRecord
  belongs_to :reservation
  belongs_to :bottle_lot
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :messages, dependent: :destroy
  has_many :reservations
  has_many :bottle_lots
  has_many :conversations, dependent: :destroy
  has_many :cellars, dependent: :destroy

  validates :first_name, presence: true
  validates :last_name, presence: true
  # validates :birthdate, presence: true
  # validates :birthdate, timeliness: { on_or_before: lambda { Date.current }, type: :date }

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]

  def self.find_for_facebook_oauth(auth)
    user_params = auth.to_h.slice(:provider, :uid)
    user_params.merge! auth.info.slice(:email, :first_name, :last_name)
    user_params[:facebook_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)

    user = User.where(provider: auth.provider, uid: auth.uid).first
    user ||= User.where(email: auth.info.email).first # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
    end

    return user
  end
end

app/controllers/admin/cellars_controller.rb
class Admin::CellarsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
  end

  def new
    @cellar = Cellar.new
  end

  def edit
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :birthdate])
  end

end

app/controllers/caves_controller.rb
class CavesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end

end

app/controllers/cellars_controller.rb
class CellarsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    if search_params[:space_available].blank?
      @cellars = Cellar.all
    else
      @cellars = Cellar.where(search_params)
    end

    @cellars_maps = Cellar.where.not(latitude: nil, longitude: nil)
    @hash = Gmaps4rails.build_markers(@cellars_maps) do |cellar, marker|
      marker.lat cellar.latitude
      marker.lng cellar.longitude
    end

  end

  def show
    @cellar = Cellar.find(params[:id])
    @cellar_coordinates = { lat: @cellar.latitude, lng: @cellar.longitude }

    @hash = Gmaps4rails.build_markers(@cellar) do |cellar, marker|
      marker.lat cellar.latitude
      marker.lng cellar.longitude
    end
    @message = Message.new
  end

  def create
    @cellar = Cellar.new(cellar_params)
    @cellar.user = current_user

    if @cellar.save
      redirect_to cellar_path(@cellar)
    else
      render :new
    end
  end

  private

  def cellar_params
    params.require(:cellar).permit(:name, :description, :address, :space_available, :price_per_month, :kind, :temperature, :open_hour, photos: [])
  end

  def search_params
    params.require(:search).permit(:space_available)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  before_action :find_cellar, only: [ :new, :create ]

  def create
    if params[:cellar_id]
      @conversation = Conversation.where(user: current_user, cellar: @cellar).take
      @conversation = Conversation.create(user: current_user, cellar: @cellar) unless @conversation
    else
      @conversation = Conversation.find(params[:conversation_id])
    end

    @message = current_user.messages.new(message_params)
    @message.conversation = @conversation
    if @message.save
      redirect_to conversation_path(@conversation)
    else
      render :new
    end
  end

  def new
    @message = Message.new
  end

  private

  def find_cellar
    @cellar = Cellar.find(params[:cellar_id]) if params[:cellar_id]
  end

  def message_params
    params.require(:message).permit(:content)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
    @cellars = Cellar.where.not(latitude: nil, longitude: nil)

    @hash = Gmaps4rails.build_markers(@cellars) do |cellar, marker|
      marker.lat cellar.latitude
      marker.lng cellar.longitude
      # marker.infowindow render_to_string(partial: "/flats/map_box", locals: { flat: flat })
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def dashboard
    @user = User.find(current_user.id)

    @cellars = @user.cellars.all
  end

  def show
    @user = User.find(params[:id])
    @cellars = @user.cellars.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def yield_with_default(holder, default)
    if content_for?(holder)
      content_for(holder).squish
    else
      default
    end
  end
end

app/helpers/bottle_lots_helper.rb
module BottleLotsHelper
end

app/helpers/caves_helper.rb
module CavesHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/cellars/_form.html.erb
<div class="container">
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= simple_form_for @cellar do |f| %>
      <%= f.error_notification %>
      <%= f.input :description %>
      <%= f.input :address %>
      <%= f.input :space_available %>
      <%= f.input :price_per_month %>
      <%= f.input :kind, collection: [ "Wine Refrigerator", "Wine Cellar"] %>
      <%= f.input :temperature %>
      <%= f.input :open_hour %>
      <%= f.input :photos, as: :attachinary %>
      <div class="text-center">
        <%= f.button :submit, class: "btn btn-primary" %>
      </div>
      <% end %>
    </div>
</div>
</div>

app/views/admin/cellars/edit.html.erb
<p>edit a cellar </p>

app/views/admin/cellars/index.html.erb
<p>GROSSES CAVES</p>

app/views/admin/cellars/new.html.erb
<div class="text-center">
  <div class="title">
    <h2> Please describe your Cellar </h2>
  </div>
</div>

<%= render "form" %>

app/views/cellars/index.html.erb
<h1 style="">Cellars' List</h1>

<div class="container">
  <div class="row">
    <% @cellars.each do |c| %>
    <div class="col-xs-12 col-sm-4">
      <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= image_path "wine_cellar.jpg" %>');">
        <div class="card-category"><%= c.kind %></div>
          <div class="card-description">
            <h2><%= c.user.first_name %>'s Cellar</h2>
            <p><%= c.address %> </p>
          </div>
        <div class="card-user">
          <%= c.price_per_month %> €
        </div>
        <%= link_to "", cellar_path(c), class: "card-link" %>
      </div>
    </div>
  <% end %>
  </div>
</div>

<hr>
<h1 style="">Overview</h1>

<div id="map" style="width: 100%; height: 400px; margin-bottom: 10px">
  <% content_for(:after_js) do %>
    <script>
      $(document).on('ready', function() {

        var handler = Gmaps.build('Google');
        handler.buildMap({ provider: { scrollwheel: false, zoomcontrol: true, draggable: true },internal: { id: 'map' } }, function() {
            markers = handler.addMarkers(<%= raw @hash.to_json %>);
            handler.bounds.extendWith(markers);
            handler.fitMapToBounds(markers);
        });
      });
    </script>
  <% end %>
</div>

app/views/cellars/show.html.erb
<% content_for :title, "#{@cellar.user.first_name}'s Cellar | Mister Cocktail" %>
<div class="main-picture">
  <% if @cellar.photos.empty? %>
    <%= image_tag "wine_cellar.jpg", class: "image-header" %>
  <% else %>
    <% @cellar.photos.each do |photo| %>
      <%= cl_image_tag photo.path, class: "image-header" %>
    <% end %>
  <% end %>
</div>

<div class="details text-center">
  <div>
    <p>
    <h2><i class="fa fa-braille" aria-hidden="true"></i></h2>
    <strong><%= @cellar.space_available %></strong> Emplacement disponible
    </p>
  </div>


  <div>
    <p>
    <h2><i class="fa fa-eur" aria-hidden="true"></i></h2>
    <strong><%= @cellar.price_per_month %>€</strong> Abonnement Mensuel
    </p>
  </div>

  <div>
    <p>
    <h2><i class="fa fa-building-o" aria-hidden="true"></i></i></h2>
    <strong><%= @cellar.kind %></strong>
    </p>
  </div>

  <div>
    <p>
    <h2><i class="fa fa-fire" aria-hidden="true"></i></h2>
    <strong><%= @cellar.temperature %>°C</strong>
    </p>
  </div>

  <div>
    <p>
    <h2><i class="fa fa-hourglass-end" aria-hidden="true"></i></h2>
    <strong><%= @cellar.open_hour %></strong>
    </p>
  </div>
</div>

<hr>
<div class="text-center">
  <h2><%= @cellar.user.first_name %> 's Cellar </h2>
  <!-- <h5><%= @cellar.description %></h5>
   -->
  <h4><%= @cellar.address %></h4>

  <div class="user-infos">
    <%= link_to user_profile_path(@cellar.user) do %>
    <%= @cellar.user.first_name %> <%= @cellar.user.last_name %>
    <% end %>
  </div>
</div>

<hr>

<div class="details text-center">
 <!-- Button trigger modal -->
  <a data-toggle="modal" href="#myModal" class="btn btn-danger btn-lg">Send a message</a>

  <!-- Modal Conversation -->
  <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">Send a message to <%= @cellar.user.first_name %></h4>
        </div>
        <div class="modal-body">
          <%= simple_form_for @message, url: cellar_messages_path(@cellar)  do |f| %>
          <%= f.input :content %>
        </div>
        <div class="modal-footer">
          <%= f.button :submit, class: "btn btn-primary btn-lg" %>
          <% end %>
        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->

  <%= link_to "Book the cave!", new_cellar_reservation_path(@cellar), class: "btn btn-primary btn-lg" %>
</div>

<div id="map" style="width: 100%; height: 400px; margin: 15px 0px">
  <% content_for(:after_js) do %>
    <script>
      $(document).on('ready', function() {
        var handler = Gmaps.build('Google');
        handler.buildMap({ provider: { scrollwheel: false, zoomcontrol: true,
          draggable: true }, internal: { id: 'map' } }, function() {

          markers = handler.addMarkers(<%= raw @hash.to_json %>);
          handler.bounds.extendWith(markers);
          handler.fitMapToBounds();
          handler.getMap().setZoom(13);
        });
      });
    </script>
  <% end %>
</div>

<div id="reviews">
  <% if @cellar.any_reviews? %>
    <% @cellar.reservations.each do |reservation| %>
      <%= reservation.review %>
    <% end %>
  <% else %>
    Be the first to leave a review for <%= @cellar.user.first_name %>
  <% end %>
</div>