config/routes.rb
Rails.application.routes.draw do

  get 'dashboard' => 'users#dashboard', as: "user_dashboard"

  get 'profile/:id' => 'users#show', as: "user_profile"

  resources :conversations, only: [:index, :show] do
    resources :messages, only: [:create]
  end


  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
    root to: 'pages#home'

  resources :cellars, only: [:index, :show, :create, :update, :destroy] do
    resources :reservations, only: [:create, :new, :show, :destroy, :update]
    resources :messages, only: [:create, :new, :index]
  end

  resources :reservations, only: [] do
    resources :reservation_bottles, only: [:create, :show, :destroy]
  end

  namespace :admin do
    resources :bottle_lots, only: [:new, :index, :create, :show]
    resources :cellars, only: [:new, :index, :edit]
    resources :reservations, only: [:index, :show]
  end

  mount Attachinary::Engine => "/attachinary"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :user
  belongs_to :cellar
  has_many :messages
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  def index
    @conversations = current_user.conversations.all
  end

  def show
    @conversation = Conversation.find(params[:id])
    @message = Message.new

    @messages = @conversation.messages
  end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/index.html.erb
<div class="subnav">
  <%= link_to "Dashboard", user_dashboard_path, class: "subtitle" %>
  <%= link_to "Inbox", conversations_path, class: "subtitle active" %>
</div>



<% @conversations.each do |conversation| %>
<%= link_to conversation_path(conversation) do %>
<div class="product">
  <div class='product-upvote'>
    <div class='product-count'><i class="fa fa-envelope" aria-hidden="true"></i></div>
  </div>
  <%= image_tag "wine_cellar.jpg", class: "product-image hidden-xs" %>
  <div class='product-body'>
    <h3><%= conversation.cellar.user.first_name %> <%= conversation.cellar.user.last_name %></h3>
    <p><%= conversation.messages.last.content %></p>
  </div>
  <ul class="list-inline product-controls hidden-sm hidden-xs">
    <li><%= conversation.messages.last.created_at.strftime("%w %A %B") %></li>
  </ul>
</div>
<% end %>
<% end %>

app/views/conversations/show.html.erb
<div class="subnav">
  <%= link_to "Dashboard", user_dashboard_path, class: "subtitle" %>
  <%= link_to "Inbox", conversations_path, class: "subtitle dash" %>
  <%= link_to "Message", conversations_path, class: "subtitle active message" %>
</div>


<blockquote class="chat">
<% @messages.each do |message| %>
<div class="iphone <%=  message.user == current_user ? "me" : "them" %>">
    <strong><%= message.user.first_name %> <%= message.user.last_name %> :</strong><br>
 <%= message.content %>
</div>


<% end %>


<div class="reply-box">
  <%= simple_form_for [@conversation, @message] do |f| %>
    <%= f.input :content, label: false %>
    <%= f.button :submit, class: "btn btn-primary" %>
    <% end %>
</div>

</blockquote>