config/routes.rb
Rails.application.routes.draw do

  get 'dashboard' => 'users#dashboard', as: "user_dashboard"

  get 'profile/:id' => 'users#show', as: "user_profile"

  resources :conversations, only: [:index, :show] do
    resources :messages, only: [:create]
  end


  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
    root to: 'pages#home'

  resources :cellars, only: [:index, :show, :create, :update, :destroy] do
    resources :reservations, only: [:create, :new, :show, :destroy, :update]
    resources :messages, only: [:create, :new, :index]
  end

  resources :reservations, only: [] do
    resources :reservation_bottles, only: [:create, :show, :destroy]
  end

  namespace :admin do
    resources :bottle_lots, only: [:new, :index, :create, :show]
    resources :cellars, only: [:new, :index, :edit]
    resources :reservations, only: [:index, :show]
  end

  mount Attachinary::Engine => "/attachinary"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :messages, dependent: :destroy
  has_many :reservations
  has_many :bottle_lots
  has_many :conversations, dependent: :destroy
  has_many :cellars, dependent: :destroy

  validates :first_name, presence: true
  validates :last_name, presence: true
  # validates :birthdate, presence: true
  # validates :birthdate, timeliness: { on_or_before: lambda { Date.current }, type: :date }

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]

  def self.find_for_facebook_oauth(auth)
    user_params = auth.to_h.slice(:provider, :uid)
    user_params.merge! auth.info.slice(:email, :first_name, :last_name)
    user_params[:facebook_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)

    user = User.where(provider: auth.provider, uid: auth.uid).first
    user ||= User.where(email: auth.info.email).first # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
    end

    return user
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
 def facebook
    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def dashboard
    @user = User.find(current_user.id)

    @cellars = @user.cellars.all
  end

  def show
    @user = User.find(params[:id])
    @cellars = @user.cellars.all
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/dashboard.html.erb
<% content_for :title, "#{current_user.first_name} | WineSitter Dashboard" %>
<div class="subnav">
  <%= link_to "Dashboard", user_dashboard_path, class: "subtitle dash-active" %>
  <%= link_to "Inbox", conversations_path, class: "subtitle dash" %>
</div>






<h2> Bienvenue <%= link_to user_profile_path(current_user) do %><%= current_user.first_name %> <% end %> </h2>

<div class="container">
  <div class="row">
      <div class="bottles">
      <h3>My Bottles  <%= link_to new_admin_bottle_lot_path do %><i class="fa fa-plus" aria-hidden="true"></i><% end %></h3>
      <% @user.bottle_lots.each do |bottle| %>
        <div class="col-xs-12 col-sm-4">
          <strong><%= bottle.quantity %></strong> <%= bottle.dimension %><br>
          <h4><%= bottle.appelation %></h4>
          <h5><%= bottle.year %></h5>
          <h5><%= bottle.color %></h5>
        </div>
      <% end %>
      </div>
    </div>

    <div class="row">
      <div class="cellar">
       <h3>My Cellars  <%= link_to new_admin_cellar_path do %><i class="fa fa-plus" aria-hidden="true"></i><% end %></h3>
            <% @cellars.each do |c| %>
            <div class="col-xs-12 col-sm-4">
              <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= image_path "wine_cellar.jpg" %>');">
                <div class="card-category"><%= c.kind %></div>
                  <div class="card-description">
                    <h2><%= @user.first_name %>'s Cellar </h2>
                    <p><%= c.address %> </p>
                  </div>
                <div class="card-user">
                  <%= c.price_per_month %> €
                <%= link_to "", cellar_path(c), class: "card-link" %>
              </div>
              </div>
            </div>
            <% end %>
          </div>
      </div>

      <div class="row">
          <div class="reservation">
          <h3>My Reservations  </h3>
          <% @user.bottle_lots.each do |bottle_lot| %>
            <% bottle_lot.reservation_bottles.each do |reservation_bottle| %>
             <p>Reservation numéro : <%= reservation_bottle.reservation.id %></p>
             <p>Date de début de réservation : <%= reservation_bottle.reservation.check_in %> date de fin de réservation :  <%= reservation_bottle.reservation.check_out %></p> <%= link_to  reservation_reservation_bottle_path(reservation_bottle.reservation.id, reservation_bottle.id) do %><i class="fa fa-trash-o" aria-hidden="true"></i>  <% end %>

                <%= simple_form_for [reservation_bottle.reservation.cellar, reservation_bottle.reservation] do |form| %>
                  <%= form.input :review %>
                  <%= form.button :submit %>
                <% end %>

             <hr>
            <% end %>
          <% end %>
          </div>
      </div>
</div>

app/views/users/show.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(235,51,73,0.6) 0%, rgba(244,92,67,0.6) 50%), url('<%= image_path "cellar_background.jpg" %>');">
 <div class="profil-user">
  <div class="image-user">
    <%= image_tag "http://placehold.it/150x150" %>
  </div>
  <div class="text-user">
    <h1>Hello, my name is <%= @user.first_name %></h1>
      <h5><strong><%= @user.first_name %> <%= @user.last_name %></strong> · Member since <strong><%= @user.created_at.strftime("%B %Y") %></strong></h5>
  </div>
</div>

</div>



<div class="container">
<h1 class="text-center"><%= @user.first_name %> | Cellars' List</h1>
<div class="row">
      <% @cellars.each do |c| %>
      <div class="col-xs-12 col-sm-4">
        <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= image_path "wine_cellar.jpg" %>');">
          <div class="card-category"><%= c.kind %></div>
            <div class="card-description">
              <h2><%= c.user.first_name %>'s Cellar</h2>
              <p><%= c.address %> </p>
            </div>
          <div class="card-user">
            <%= c.price_per_month %> €
          <%= link_to "", cellar_path(c), class: "card-link" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<hr>