config/routes.rb
Rails.application.routes.draw do

  get 'dashboard' => 'users#dashboard', as: "user_dashboard"

  get 'profile/:id' => 'users#show', as: "user_profile"

  resources :conversations, only: [:index, :show] do
    resources :messages, only: [:create]
  end


  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
    root to: 'pages#home'

  resources :cellars, only: [:index, :show, :create, :update, :destroy] do
    resources :reservations, only: [:create, :new, :show, :destroy, :update]
    resources :messages, only: [:create, :new, :index]
  end

  resources :reservations, only: [] do
    resources :reservation_bottles, only: [:create, :show, :destroy]
  end

  namespace :admin do
    resources :bottle_lots, only: [:new, :index, :create, :show]
    resources :cellars, only: [:new, :index, :edit]
    resources :reservations, only: [:index, :show]
  end

  mount Attachinary::Engine => "/attachinary"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bottle_lot.rb
class BottleLot < ApplicationRecord
  belongs_to :user
  has_many :reservation_bottles
  has_many :reservations, through: :reservation_bottles

  validates :year, presence: true
  validates :appelation, presence: true
  validates :quantity, presence: true


  def to_s
    "#{dimension} - #{quantity}"
  end

end

app/models/cave.rb
class Cave < ApplicationRecord
  belongs_to :user
  has_many :reservations, dependent: :destroy
  has_many :messages, dependent: :destroy

  validates :description, presence: true
  validates :address, presence: true
  validates :price_per_month, presence: true
  validates :type, presence: true

end

app/models/cellar.rb
class Cellar < ApplicationRecord
  belongs_to :user
  has_many :reservations, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :conversations, dependent: :destroy

  validates :description, presence: true
  validates :address, presence: true
  validates :price_per_month, presence: true
  validates :kind, presence: true

  has_attachments :photos, maximum: 3

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  def any_reviews?
    self.reservations.any? { |reservation| reservation.review.present? }
  end

end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :user
  belongs_to :cellar
  has_many :messages
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :conversation

  validates :content, presence: true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :cellar
  belongs_to :user
  has_many :reservation_bottles
  has_many :bottle_lots, through: :reservation_bottles

  validates :check_in, presence: true
  validates :check_out, presence: true

end

app/models/reservation_bottle.rb
class ReservationBottle < ApplicationRecord
  belongs_to :reservation
  belongs_to :bottle_lot
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :messages, dependent: :destroy
  has_many :reservations
  has_many :bottle_lots
  has_many :conversations, dependent: :destroy
  has_many :cellars, dependent: :destroy

  validates :first_name, presence: true
  validates :last_name, presence: true
  # validates :birthdate, presence: true
  # validates :birthdate, timeliness: { on_or_before: lambda { Date.current }, type: :date }

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]

  def self.find_for_facebook_oauth(auth)
    user_params = auth.to_h.slice(:provider, :uid)
    user_params.merge! auth.info.slice(:email, :first_name, :last_name)
    user_params[:facebook_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)

    user = User.where(provider: auth.provider, uid: auth.uid).first
    user ||= User.where(email: auth.info.email).first # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
    end

    return user
  end
end

app/controllers/caves_controller.rb
class CavesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end

end

app/controllers/cellars_controller.rb
class CellarsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    if search_params[:space_available].blank?
      @cellars = Cellar.all
    else
      @cellars = Cellar.where(search_params)
    end

    @cellars_maps = Cellar.where.not(latitude: nil, longitude: nil)
    @hash = Gmaps4rails.build_markers(@cellars_maps) do |cellar, marker|
      marker.lat cellar.latitude
      marker.lng cellar.longitude
    end

  end

  def show
    @cellar = Cellar.find(params[:id])
    @cellar_coordinates = { lat: @cellar.latitude, lng: @cellar.longitude }

    @hash = Gmaps4rails.build_markers(@cellar) do |cellar, marker|
      marker.lat cellar.latitude
      marker.lng cellar.longitude
    end
    @message = Message.new
  end

  def create
    @cellar = Cellar.new(cellar_params)
    @cellar.user = current_user

    if @cellar.save
      redirect_to cellar_path(@cellar)
    else
      render :new
    end
  end

  private

  def cellar_params
    params.require(:cellar).permit(:name, :description, :address, :space_available, :price_per_month, :kind, :temperature, :open_hour, photos: [])
  end

  def search_params
    params.require(:search).permit(:space_available)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
    @cellars = Cellar.where.not(latitude: nil, longitude: nil)

    @hash = Gmaps4rails.build_markers(@cellars) do |cellar, marker|
      marker.lat cellar.latitude
      marker.lng cellar.longitude
      # marker.infowindow render_to_string(partial: "/flats/map_box", locals: { flat: flat })
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def dashboard
    @user = User.find(current_user.id)

    @cellars = @user.cellars.all
  end

  def show
    @user = User.find(params[:id])
    @cellars = @user.cellars.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def yield_with_default(holder, default)
    if content_for?(holder)
      content_for(holder).squish
    else
      default
    end
  end
end

app/helpers/bottle_lots_helper.rb
module BottleLotsHelper
end

app/helpers/caves_helper.rb
module CavesHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render "pages/charlydev"  %>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title><%= yield_with_default(:title, "WineSitter | Store your wine like pros. ") %></title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>
  <body>
  <%= render 'shared/navbar' %>
  <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag "https://maps.google.com/maps/api/js?key=AIzaSyC99U2We_TH2BPyTwB2RZ2b5RH_ZQrr46I" %>
    <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/markerclusterer/src/markerclusterer_compiled.js" %>

    <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js" %>

    <%= javascript_include_tag 'application' %>
    <%= yield(:after_js) %>
    <%= cloudinary_js_config %>
  </body>
</html>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.svg" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Search form -->
      <%= simple_form_for :search, url: cellars_path, method: :get, html: { class: "navbar-wagon-search" } do |f| %>
          <%= f.input :space_available, label: false, placeholder: "How much bottles?", class: "navbar-wagon-search-input"%>
          <%= button_tag type: :submit, class: "navbar-wagon-search-btn" do %>
            <i class="fa fa-search"></i>
          <% end %>
        <% end %>


    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

      <!-- Notification -->
      <%= link_to "#", class: "navbar-wagon-item navbar-wagon-link" do %>
        <%= link_to conversations_path do %>
        <div class="badge-container">
          <i class="fa fa-envelope-o"></i>
          <div  class="badge badge-blue"><%= current_user.messages.count %></div>
        </div>
        <% end %>
      <% end %>

      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "volpeo.jpg", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to user_dashboard_path do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to root_path do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>

      <!-- Login text link -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>

    <!-- Button (call-to-action) -->
    <%= link_to t(".top_call_to_action", default: "Add a cellar"), new_admin_cellar_path , class: "navbar-wagon-item navbar-wagon-button btn" %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
  <% if user_signed_in? && current_user.facebook_picture_url %>
  <%= image_tag current_user.facebook_picture_url, height: 50, width: 50 %>
<% end %>
</div>